In [1]:
import numpy as np
import pandas as pd

In [2]:
tourist = pd.read_csv("Tourist Places.csv")
tourist

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Tourist attraction,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Tourist attraction,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",·,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",·,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Tourist attraction,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Hindu temple, believed to be hundreds of years...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Theme park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",·,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
738,Maharashtra,Pune,Lonavala,Adoshi Dam,4.7,Tourist attraction,"Q85C+W7V, Aadoshi, Maharashtra 410203","18.759924461011586, 73.32064211100874",NaN,https://www.google.com/maps/place/Adoshi+Dam/d...,https://lh5.googleusercontent.com/p/AF1QipO3IT...,NaN
739,Maharashtra,Pune,Lonavala,Reversing Station,3.5,Railway services,"Q985+GPQ, Lonavla, Maharashtra 410203","18.766406075808653, 73.35932651100879",NaN,https://www.google.com/maps/place/Reversing+St...,https://lh5.googleusercontent.com/p/AF1QipNiDL...,NaN
740,Maharashtra,Pune,Lonavala,Karla,5.0,Tourist attraction,"Omii Creations, near hi5 broadband service, Ka...","18.759636196636702, 73.47993849751768",NaN,https://www.google.com/maps/place/Karla/data=!...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
741,Maharashtra,Pune,Lonavala,RAJMACHI CAMPSITE,5.0,Campground,"Udhewadi, Gawliwada, Lonavla, Maharashtra 410401","18.754652544399313, 73.40623399751769",NaN,https://www.google.com/maps/place/RAJMACHI+CAM...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
742,Maharashtra,Pune,Lonavala,Pawna lake camping,4.3,Campground,"PCPQ+4G6, Kevaregaon, Lonavla, Maharashtra 410406","18.735325008824532, 73.4387587686811",NaN,https://www.google.com/maps/place/Pawna+lake+c...,https://lh5.googleusercontent.com/p/AF1QipMKT5...,NaN

In [3]:
tourist.head()

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Tourist attraction,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Tourist attraction,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",·,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",·,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Tourist attraction,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Hindu temple, believed to be hundreds of years...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Theme park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",·,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN

In [4]:
tourist.isnull().sum()

Palce_State            0
Place_District         0
Place_City             0
Place_Name             0
Place_Rating          66
Place_Category         0
Place_Address          0
Place_GPS_Code         2
Place_Description    324
Place_Map_Link         0
Place_Photo            0
Unnamed: 11          733
dtype: int64

In [5]:
tourist.duplicated().sum()

0

In [6]:
tourist = tourist.dropna(subset=['Place_Rating'])
tourist

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Tourist attraction,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Tourist attraction,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",·,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",·,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Tourist attraction,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Hindu temple, believed to be hundreds of years...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Theme park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",·,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
738,Maharashtra,Pune,Lonavala,Adoshi Dam,4.7,Tourist attraction,"Q85C+W7V, Aadoshi, Maharashtra 410203","18.759924461011586, 73.32064211100874",NaN,https://www.google.com/maps/place/Adoshi+Dam/d...,https://lh5.googleusercontent.com/p/AF1QipO3IT...,NaN
739,Maharashtra,Pune,Lonavala,Reversing Station,3.5,Railway services,"Q985+GPQ, Lonavla, Maharashtra 410203","18.766406075808653, 73.35932651100879",NaN,https://www.google.com/maps/place/Reversing+St...,https://lh5.googleusercontent.com/p/AF1QipNiDL...,NaN
740,Maharashtra,Pune,Lonavala,Karla,5.0,Tourist attraction,"Omii Creations, near hi5 broadband service, Ka...","18.759636196636702, 73.47993849751768",NaN,https://www.google.com/maps/place/Karla/data=!...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
741,Maharashtra,Pune,Lonavala,RAJMACHI CAMPSITE,5.0,Campground,"Udhewadi, Gawliwada, Lonavla, Maharashtra 410401","18.754652544399313, 73.40623399751769",NaN,https://www.google.com/maps/place/RAJMACHI+CAM...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
742,Maharashtra,Pune,Lonavala,Pawna lake camping,4.3,Campground,"PCPQ+4G6, Kevaregaon, Lonavla, Maharashtra 410406","18.735325008824532, 73.4387587686811",NaN,https://www.google.com/maps/place/Pawna+lake+c...,https://lh5.googleusercontent.com/p/AF1QipMKT5...,NaN

In [7]:
num_rating_df = tourist.groupby('Place_Category').count()['Place_Rating'].reset_index()
num_rating_df.rename(columns={'Place_Rating':'num_ratings'},inplace=True)

In [8]:
num_rating_df

             Place_Category  num_ratings
0   Adventure Sports Center            1
1      Agricultural service            1
2            Amusement Park            6
3          Amusement center            1
4            Amusement park            4
..                      ...          ...
75               Wax museum            2
76            Wildlife Park            1
77                   Winery            1
78        Wrestling Stadium            1
79                      Zoo            5

[80 rows x 2 columns]

In [9]:
avg_rating_df = tourist.groupby('Place_Category').mean()['Place_Rating'].reset_index()
avg_rating_df.rename(columns={'Place_Rating':'avg_rating'},inplace=True)
avg_rating_df

             Place_Category  avg_rating
0   Adventure Sports Center       4.100
1      Agricultural service       4.300
2            Amusement Park       4.000
3          Amusement center       4.500
4            Amusement park       3.925
..                      ...         ...
75               Wax museum       3.750
76            Wildlife Park       4.500
77                   Winery       4.400
78        Wrestling Stadium       4.500
79                      Zoo       4.040

[80 rows x 2 columns]

In [10]:
popular_df = num_rating_df.merge(avg_rating_df,on='Place_Category')
popular_df

             Place_Category  num_ratings  avg_rating
0   Adventure Sports Center            1       4.100
1      Agricultural service            1       4.300
2            Amusement Park            6       4.000
3          Amusement center            1       4.500
4            Amusement park            4       3.925
..                      ...          ...         ...
75               Wax museum            2       3.750
76            Wildlife Park            1       4.500
77                   Winery            1       4.400
78        Wrestling Stadium            1       4.500
79                      Zoo            5       4.040

[80 rows x 3 columns]

In [11]:
popular_df = popular_df[popular_df['num_ratings']>=2].sort_values('avg_rating',ascending=False).head(20)
popular_df

             Place_Category  num_ratings  avg_rating
49          National forest            2    4.850000
50          Nature preserve            4    4.775000
20                     Fort            5    4.700000
15                   Castle            2    4.700000
29             Hindu Temple            5    4.660000
27             Hill Station            2    4.650000
7                     Beach           16    4.612500
13               Campground            5    4.600000
56             Public beach            4    4.575000
30             Hindu temple           79    4.568354
35  Historical place museum            2    4.550000
70               View Point           27    4.537037
45            Mountain peak            5    4.520000
43            Memorial park            3    4.500000
6                    Ashram            2    4.500000
21                 Fortress           27    4.488889
26              Hiking area            6    4.466667
69       Tourist attraction          277    4.410830
33      Historical landmark           23    4.404348
61              Scenic spot            4    4.400000

In [12]:
tourist1 = tourist[['Place_Name' ,'Place_City', 'Place_Category', 'Place_Description', 'Place_Rating']]
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Tourist attraction,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Tourist attraction,·,3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,·,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Tourist attraction,"Hindu temple, believed to be hundreds of years...",4.7
4,Magic Garden,Ratnagiri,Theme park,·,4.1
...,...,...,...,...,...
738,Adoshi Dam,Lonavala,Tourist attraction,NaN,4.7
739,Reversing Station,Lonavala,Railway services,NaN,3.5
740,Karla,Lonavala,Tourist attraction,NaN,5.0
741,RAJMACHI CAMPSITE,Lonavala,Campground,NaN,5.0
742,Pawna lake camping,Lonavala,Campground,NaN,4.3

In [13]:
tourist1['Place_Name'].duplicated().sum()

0

In [14]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [15]:
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Tourist attraction,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Tourist attraction,·,3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,·,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Tourist attraction,"Hindu temple, believed to be hundreds of years...",4.7
4,Magic Garden,Ratnagiri,Theme park,·,4.1
...,...,...,...,...,...
738,Adoshi Dam,Lonavala,Tourist attraction,NaN,4.7
739,Reversing Station,Lonavala,Railway services,NaN,3.5
740,Karla,Lonavala,Tourist attraction,NaN,5.0
741,RAJMACHI CAMPSITE,Lonavala,Campground,NaN,5.0
742,Pawna lake camping,Lonavala,Campground,NaN,4.3

In [16]:
tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x:x.split())

C:\Users\HP\AppData\Local\Temp/ipykernel_4844/4200446306.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x:x.split())

In [17]:
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,"[Tourist, attraction]",Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,"[Tourist, attraction]",·,3.0
2,Jaigad Light House,Ratnagiri,"[Tourist, attraction]",·,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,"[Tourist, attraction]","Hindu temple, believed to be hundreds of years...",4.7
4,Magic Garden,Ratnagiri,"[Theme, park]",·,4.1
...,...,...,...,...,...
738,Adoshi Dam,Lonavala,"[Tourist, attraction]",NaN,4.7
739,Reversing Station,Lonavala,"[Railway, services]",NaN,3.5
740,Karla,Lonavala,"[Tourist, attraction]",NaN,5.0
741,RAJMACHI CAMPSITE,Lonavala,[Campground],NaN,5.0
742,Pawna lake camping,Lonavala,[Campground],NaN,4.3

In [18]:
tourist1['Place_Category'] = tourist1['Place_Category'].apply(collapse)

C:\Users\HP\AppData\Local\Temp/ipykernel_4844/3107620817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_Category'] = tourist1['Place_Category'].apply(collapse)

In [19]:
tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x: "".join(x))
tourist1.head()

C:\Users\HP\AppData\Local\Temp/ipykernel_4844/2585800139.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x: "".join(x))

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Touristattraction,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Touristattraction,·,3.0
2,Jaigad Light House,Ratnagiri,Touristattraction,·,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Touristattraction,"Hindu temple, believed to be hundreds of years...",4.7
4,Magic Garden,Ratnagiri,Themepark,·,4.1

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100,stop_words='english')

In [21]:
vector = cv.fit_transform(tourist1['Place_Category']).toarray()

In [22]:
vector.shape

(677, 75)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
similarity = cosine_similarity(vector)

In [25]:
similarity

array([[1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 1., 1.]])

In [26]:
tourist1[tourist1['Place_Name'] == 'Prachin Konkan'].index[0]

0

In [27]:
def recommend(place):
    index = tourist1[tourist1['Place_Name'] == place].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(tourist1.iloc[i[0]].Place_Name)

In [28]:
recommend('Prachin Konkan')

Shree Mahalakshmi's House of Wax
Jaigad Light House
Shree Ganpatipule Mandir
Boat Club Beach
Mandavi Beach