In [1]:
import numpy as np
import pandas as pd

In [2]:
tourist = pd.read_csv("Final Tourist Places.csv")
tourist

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Museum,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Museum,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",-,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",-,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Temple,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Temple, believed to be hundreds of years old, ...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",-,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
724,Maharashtra,Pune,Lonavala,Indrayani view point,5.0,View Point,"QH82+GF8, Kamshet, Maharashtra 410405","18.766374275822972, 73.55119666868151",NaN,https://www.google.com/maps/place/Indrayani+vi...,https://lh5.googleusercontent.com/p/AF1QipNzt6...,NaN
725,Maharashtra,Pune,Lonavala,Adoshi Dam,4.7,Tourist attraction,"Q85C+W7V, Aadoshi, Maharashtra 410203","18.759924461011586, 73.32064211100874",NaN,https://www.google.com/maps/place/Adoshi+Dam/d...,https://lh5.googleusercontent.com/p/AF1QipO3IT...,NaN
726,Maharashtra,Pune,Lonavala,Karla,5.0,Tourist attraction,"Omii Creations, near hi5 broadband service, Ka...","18.759636196636702, 73.47993849751768",NaN,https://www.google.com/maps/place/Karla/data=!...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
727,Maharashtra,Pune,Lonavala,RAJMACHI CAMPSITE,5.0,Tourist attraction,"Udhewadi, Gawliwada, Lonavla, Maharashtra 410401","18.754652544399313, 73.40623399751769",NaN,https://www.google.com/maps/place/RAJMACHI+CAM...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
728,Maharashtra,Pune,Lonavala,Pawna lake camping,4.3,Tourist attraction,"PCPQ+4G6, Kevaregaon, Lonavla, Maharashtra 410406","18.735325008824532, 73.4387587686811",NaN,https://www.google.com/maps/place/Pawna+lake+c...,https://lh5.googleusercontent.com/p/AF1QipMKT5...,NaN

In [3]:
tourist.head()

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Museum,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Museum,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",-,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",-,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Temple,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Temple, believed to be hundreds of years old, ...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",-,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN

In [4]:
tourist.isnull().sum()

Palce_State            0
Place_District         0
Place_City             0
Place_Name             0
Place_Rating           0
Place_Category         0
Place_Address          0
Place_GPS_Code         0
Place_Description    312
Place_Map_Link         0
Place_Photo            0
Unnamed: 11          719
dtype: int64

In [5]:
tourist.duplicated().sum()

0

In [6]:
tourist = tourist.dropna(subset=['Place_Rating'])
tourist

,Palce_State,Place_District,Place_City,Place_Name,Place_Rating,Place_Category,Place_Address,Place_GPS_Code,Place_Description,Place_Map_Link,Place_Photo,Unnamed: 11
0,Maharashtra,Ratnagiri,Ratnagiri,Prachin Konkan,4.3,Museum,"Konkan Tourism Development & Research Centre, ...","17.150132380177187, 73.2754540974944",Open-air regional history museum,https://www.google.com/maps/place/Prachin+Konk...,https://lh5.googleusercontent.com/p/AF1QipP5Fh...,NaN
1,Maharashtra,Ratnagiri,Ratnagiri,Shree Mahalakshmi's House of Wax,3.0,Museum,shree mahalakshmi holiday resort ganapatipule,"17.14263843631338, 73.27201736865793",-,https://www.google.com/maps/place/Shree+Mahala...,https://lh5.googleusercontent.com/p/AF1QipOiQ_...,NaN
2,Maharashtra,Ratnagiri,Ratnagiri,Jaigad Light House,4.3,Tourist attraction,"75XR+M66, Nandivade, Maharashtra 415614","17.299180596927172, 73.1905411840057",-,https://www.google.com/maps/place/Jaigad+Light...,https://lh5.googleusercontent.com/p/AF1QipNjED...,NaN
3,Maharashtra,Ratnagiri,Ratnagiri,Shree Ganpatipule Mandir,4.7,Temple,"Ganpatipule, Maharashtra 415615","17.14452827892707, 73.26643015516721","Temple, believed to be hundreds of years old, ...",https://www.google.com/maps/place/Shree+Ganpat...,https://lh5.googleusercontent.com/p/AF1QipMEbY...,NaN
4,Maharashtra,Ratnagiri,Ratnagiri,Magic Garden,4.1,Park,"District and Tehsil Ratnagiri, Opp. Prachin Ko...","17.15010376946774, 73.27488389749446",-,https://www.google.com/maps/place/Magic+Garden...,https://lh5.googleusercontent.com/p/AF1QipNGZ9...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
724,Maharashtra,Pune,Lonavala,Indrayani view point,5.0,View Point,"QH82+GF8, Kamshet, Maharashtra 410405","18.766374275822972, 73.55119666868151",NaN,https://www.google.com/maps/place/Indrayani+vi...,https://lh5.googleusercontent.com/p/AF1QipNzt6...,NaN
725,Maharashtra,Pune,Lonavala,Adoshi Dam,4.7,Tourist attraction,"Q85C+W7V, Aadoshi, Maharashtra 410203","18.759924461011586, 73.32064211100874",NaN,https://www.google.com/maps/place/Adoshi+Dam/d...,https://lh5.googleusercontent.com/p/AF1QipO3IT...,NaN
726,Maharashtra,Pune,Lonavala,Karla,5.0,Tourist attraction,"Omii Creations, near hi5 broadband service, Ka...","18.759636196636702, 73.47993849751768",NaN,https://www.google.com/maps/place/Karla/data=!...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
727,Maharashtra,Pune,Lonavala,RAJMACHI CAMPSITE,5.0,Tourist attraction,"Udhewadi, Gawliwada, Lonavla, Maharashtra 410401","18.754652544399313, 73.40623399751769",NaN,https://www.google.com/maps/place/RAJMACHI+CAM...,https://maps.gstatic.com/tactile/pane/result-n...,NaN
728,Maharashtra,Pune,Lonavala,Pawna lake camping,4.3,Tourist attraction,"PCPQ+4G6, Kevaregaon, Lonavla, Maharashtra 410406","18.735325008824532, 73.4387587686811",NaN,https://www.google.com/maps/place/Pawna+lake+c...,https://lh5.googleusercontent.com/p/AF1QipMKT5...,NaN

In [7]:
num_rating_df = tourist.groupby('Place_Category').count()['Place_Rating'].reset_index()
num_rating_df.rename(columns={'Place_Rating':'num_ratings'},inplace=True)

In [8]:
num_rating_df

                Place_Category  num_ratings
0                     Aquarium            2
1                        Beach           29
2              Buddhist temple            1
3                    Cathedral            1
4                     Cemetery            1
5                       Church            3
6                     Fortress           50
7                       Garden            1
8                  Hiking area            1
9          Historical landmark            2
10                Holiday home            1
11                        Lake            6
12                        Mall            2
13                      Market            1
14                    Monument            2
15                      Museum           42
16                        Park           88
17          Research institute            1
18                      Temple          117
19          Tourist attraction          308
20  Tourist information center            1
21                  View Point           35
22                  Water Park            5
23                  Water park            2
24                   Waterfall           21
25                         Zoo            6

In [9]:
avg_rating_df = tourist.groupby('Place_Category').mean()['Place_Rating'].reset_index()
avg_rating_df.rename(columns={'Place_Rating':'avg_rating'},inplace=True)
avg_rating_df

                Place_Category  avg_rating
0                     Aquarium    3.500000
1                        Beach    4.596552
2              Buddhist temple    4.500000
3                    Cathedral    4.500000
4                     Cemetery    4.600000
5                       Church    4.500000
6                     Fortress    4.504000
7                       Garden    4.400000
8                  Hiking area    4.400000
9          Historical landmark    4.350000
10                Holiday home    4.000000
11                        Lake    4.416667
12                        Mall    4.400000
13                      Market    4.200000
14                    Monument    4.301773
15                      Museum    4.221429
16                        Park    4.205722
17          Research institute    4.400000
18                      Temple    4.568376
19          Tourist attraction    4.405206
20  Tourist information center    4.400000
21                  View Point    4.488571
22                  Water Park    4.020000
23                  Water park    3.600000
24                   Waterfall    4.352381
25                         Zoo    4.000000

In [10]:
popular_df = num_rating_df.merge(avg_rating_df,on='Place_Category')
popular_df

                Place_Category  num_ratings  avg_rating
0                     Aquarium            2    3.500000
1                        Beach           29    4.596552
2              Buddhist temple            1    4.500000
3                    Cathedral            1    4.500000
4                     Cemetery            1    4.600000
5                       Church            3    4.500000
6                     Fortress           50    4.504000
7                       Garden            1    4.400000
8                  Hiking area            1    4.400000
9          Historical landmark            2    4.350000
10                Holiday home            1    4.000000
11                        Lake            6    4.416667
12                        Mall            2    4.400000
13                      Market            1    4.200000
14                    Monument            2    4.301773
15                      Museum           42    4.221429
16                        Park           88    4.205722
17          Research institute            1    4.400000
18                      Temple          117    4.568376
19          Tourist attraction          308    4.405206
20  Tourist information center            1    4.400000
21                  View Point           35    4.488571
22                  Water Park            5    4.020000
23                  Water park            2    3.600000
24                   Waterfall           21    4.352381
25                         Zoo            6    4.000000

In [11]:
popular_df = popular_df[popular_df['num_ratings']>=2].sort_values('avg_rating',ascending=False).head(20)
popular_df

         Place_Category  num_ratings  avg_rating
1                 Beach           29    4.596552
18               Temple          117    4.568376
6              Fortress           50    4.504000
5                Church            3    4.500000
21           View Point           35    4.488571
11                 Lake            6    4.416667
19   Tourist attraction          308    4.405206
12                 Mall            2    4.400000
24            Waterfall           21    4.352381
9   Historical landmark            2    4.350000
14             Monument            2    4.301773
15               Museum           42    4.221429
16                 Park           88    4.205722
22           Water Park            5    4.020000
25                  Zoo            6    4.000000
23           Water park            2    3.600000
0              Aquarium            2    3.500000

In [12]:
tourist1 = tourist[['Place_Name' ,'Place_City', 'Place_Category', 'Place_Description', 'Place_Rating']]
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Museum,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Museum,-,3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,-,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Temple,"Temple, believed to be hundreds of years old, ...",4.7
4,Magic Garden,Ratnagiri,Park,-,4.1
...,...,...,...,...,...
724,Indrayani view point,Lonavala,View Point,NaN,5.0
725,Adoshi Dam,Lonavala,Tourist attraction,NaN,4.7
726,Karla,Lonavala,Tourist attraction,NaN,5.0
727,RAJMACHI CAMPSITE,Lonavala,Tourist attraction,NaN,5.0
728,Pawna lake camping,Lonavala,Tourist attraction,NaN,4.3

In [13]:
tourist1['Place_Name'].duplicated().sum()

0

In [14]:
tourist1 = tourist1.dropna(subset=['Place_Rating','Place_Description'])
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Museum,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Museum,-,3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,-,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Temple,"Temple, believed to be hundreds of years old, ...",4.7
4,Magic Garden,Ratnagiri,Park,-,4.1
...,...,...,...,...,...
717,Ulhas valley,Lonavala,Tourist attraction,Food stalls & views of nearby mountains,4.5
718,Shriwardhan Ballekilla,Lonavala,Fortress,Park with over 50 adventure activities,4.6
719,Joshis Arundhati Activities,Lonavala,Tourist attraction,Rock caves with ornate Buddhist shrines,5.0
720,Magic Mountain,Lonavala,Park,Mountain cascade tumbling into a lake,4.3
722,Tungarli Lake,Lonavala,Lake,Scenic lake with a tranquil feel,4.4

In [15]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [16]:
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Museum,Open-air regional history museum,4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Museum,-,3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,-,4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Temple,"Temple, believed to be hundreds of years old, ...",4.7
4,Magic Garden,Ratnagiri,Park,-,4.1
...,...,...,...,...,...
717,Ulhas valley,Lonavala,Tourist attraction,Food stalls & views of nearby mountains,4.5
718,Shriwardhan Ballekilla,Lonavala,Fortress,Park with over 50 adventure activities,4.6
719,Joshis Arundhati Activities,Lonavala,Tourist attraction,Rock caves with ornate Buddhist shrines,5.0
720,Magic Mountain,Lonavala,Park,Mountain cascade tumbling into a lake,4.3
722,Tungarli Lake,Lonavala,Lake,Scenic lake with a tranquil feel,4.4

In [17]:
# tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x:x.split())

In [18]:
# tourist1

In [19]:
# tourist1['Place_Category'] = tourist1['Place_Category'].apply(collapse)

In [20]:
# tourist1['Place_Category'] = tourist1['Place_Category'].apply(lambda x: "".join(x))
# tourist1.head()

In [21]:
tourist1['Place_Description'] = tourist1['Place_Description'].apply(lambda x:x.split())
tourist1

C:\Users\HP\AppData\Local\Temp/ipykernel_18116/4249195836.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_Description'] = tourist1['Place_Description'].apply(lambda x:x.split())

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,Ratnagiri,Museum,"[Open-air, regional, history, museum]",4.3
1,Shree Mahalakshmi's House of Wax,Ratnagiri,Museum,[-],3.0
2,Jaigad Light House,Ratnagiri,Tourist attraction,[-],4.3
3,Shree Ganpatipule Mandir,Ratnagiri,Temple,"[Temple,, believed, to, be, hundreds, of, year...",4.7
4,Magic Garden,Ratnagiri,Park,[-],4.1
...,...,...,...,...,...
717,Ulhas valley,Lonavala,Tourist attraction,"[Food, stalls, &, views, of, nearby, mountains]",4.5
718,Shriwardhan Ballekilla,Lonavala,Fortress,"[Park, with, over, 50, adventure, activities]",4.6
719,Joshis Arundhati Activities,Lonavala,Tourist attraction,"[Rock, caves, with, ornate, Buddhist, shrines]",5.0
720,Magic Mountain,Lonavala,Park,"[Mountain, cascade, tumbling, into, a, lake]",4.3
722,Tungarli Lake,Lonavala,Lake,"[Scenic, lake, with, a, tranquil, feel]",4.4

In [22]:
tourist1['Place_City'] = tourist1.Place_City.apply(lambda x: x[0:].split(','))
tourist1.head()

C:\Users\HP\AppData\Local\Temp/ipykernel_18116/1327157841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_City'] = tourist1.Place_City.apply(lambda x: x[0:].split(','))

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,[Ratnagiri],Museum,"[Open-air, regional, history, museum]",4.3
1,Shree Mahalakshmi's House of Wax,[Ratnagiri],Museum,[-],3.0
2,Jaigad Light House,[Ratnagiri],Tourist attraction,[-],4.3
3,Shree Ganpatipule Mandir,[Ratnagiri],Temple,"[Temple,, believed, to, be, hundreds, of, year...",4.7
4,Magic Garden,[Ratnagiri],Park,[-],4.1

In [23]:
tourist1['Place_Category'] = tourist1.Place_Category.apply(lambda x: x[0:].split(','))
tourist1.head()

C:\Users\HP\AppData\Local\Temp/ipykernel_18116/829539911.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['Place_Category'] = tourist1.Place_Category.apply(lambda x: x[0:].split(','))

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating
0,Prachin Konkan,[Ratnagiri],[Museum],"[Open-air, regional, history, museum]",4.3
1,Shree Mahalakshmi's House of Wax,[Ratnagiri],[Museum],[-],3.0
2,Jaigad Light House,[Ratnagiri],[Tourist attraction],[-],4.3
3,Shree Ganpatipule Mandir,[Ratnagiri],[Temple],"[Temple,, believed, to, be, hundreds, of, year...",4.7
4,Magic Garden,[Ratnagiri],[Park],[-],4.1

In [24]:
tourist1['tags'] = tourist1['Place_Description'] + tourist1['Place_City'] + tourist1['Place_Category']

C:\Users\HP\AppData\Local\Temp/ipykernel_18116/2311537308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tourist1['tags'] = tourist1['Place_Description'] + tourist1['Place_City'] + tourist1['Place_Category']

In [25]:
tourist1

,Place_Name,Place_City,Place_Category,Place_Description,Place_Rating,tags
0,Prachin Konkan,[Ratnagiri],[Museum],"[Open-air, regional, history, museum]",4.3,"[Open-air, regional, history, museum, Ratnagir..."
1,Shree Mahalakshmi's House of Wax,[Ratnagiri],[Museum],[-],3.0,"[-, Ratnagiri, Museum]"
2,Jaigad Light House,[Ratnagiri],[Tourist attraction],[-],4.3,"[-, Ratnagiri, Tourist attraction]"
3,Shree Ganpatipule Mandir,[Ratnagiri],[Temple],"[Temple,, believed, to, be, hundreds, of, year...",4.7,"[Temple,, believed, to, be, hundreds, of, year..."
4,Magic Garden,[Ratnagiri],[Park],[-],4.1,"[-, Ratnagiri, Park]"
...,...,...,...,...,...,...
717,Ulhas valley,[Lonavala],[Tourist attraction],"[Food, stalls, &, views, of, nearby, mountains]",4.5,"[Food, stalls, &, views, of, nearby, mountains..."
718,Shriwardhan Ballekilla,[Lonavala],[Fortress],"[Park, with, over, 50, adventure, activities]",4.6,"[Park, with, over, 50, adventure, activities, ..."
719,Joshis Arundhati Activities,[Lonavala],[Tourist attraction],"[Rock, caves, with, ornate, Buddhist, shrines]",5.0,"[Rock, caves, with, ornate, Buddhist, shrines,..."
720,Magic Mountain,[Lonavala],[Park],"[Mountain, cascade, tumbling, into, a, lake]",4.3,"[Mountain, cascade, tumbling, into, a, lake, L..."
722,Tungarli Lake,[Lonavala],[Lake],"[Scenic, lake, with, a, tranquil, feel]",4.4,"[Scenic, lake, with, a, tranquil, feel, Lonava..."

In [26]:
new = tourist1.drop(columns=['Place_City','Place_Description'])
new

,Place_Name,Place_Category,Place_Rating,tags
0,Prachin Konkan,[Museum],4.3,"[Open-air, regional, history, museum, Ratnagir..."
1,Shree Mahalakshmi's House of Wax,[Museum],3.0,"[-, Ratnagiri, Museum]"
2,Jaigad Light House,[Tourist attraction],4.3,"[-, Ratnagiri, Tourist attraction]"
3,Shree Ganpatipule Mandir,[Temple],4.7,"[Temple,, believed, to, be, hundreds, of, year..."
4,Magic Garden,[Park],4.1,"[-, Ratnagiri, Park]"
...,...,...,...,...
717,Ulhas valley,[Tourist attraction],4.5,"[Food, stalls, &, views, of, nearby, mountains..."
718,Shriwardhan Ballekilla,[Fortress],4.6,"[Park, with, over, 50, adventure, activities, ..."
719,Joshis Arundhati Activities,[Tourist attraction],5.0,"[Rock, caves, with, ornate, Buddhist, shrines,..."
720,Magic Mountain,[Park],4.3,"[Mountain, cascade, tumbling, into, a, lake, L..."
722,Tungarli Lake,[Lake],4.4,"[Scenic, lake, with, a, tranquil, feel, Lonava..."

In [27]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,Place_Name,Place_Category,Place_Rating,tags
0,Prachin Konkan,[Museum],4.3,Open-air regional history museum Ratnagiri Museum
1,Shree Mahalakshmi's House of Wax,[Museum],3.0,- Ratnagiri Museum
2,Jaigad Light House,[Tourist attraction],4.3,- Ratnagiri Tourist attraction
3,Shree Ganpatipule Mandir,[Temple],4.7,"Temple, believed to be hundreds of years old, ..."
4,Magic Garden,[Park],4.1,- Ratnagiri Park

In [28]:
new['Place_Category'] = new['Place_Category'].apply(lambda x: " ".join(x))
new.head()

,Place_Name,Place_Category,Place_Rating,tags
0,Prachin Konkan,Museum,4.3,Open-air regional history museum Ratnagiri Museum
1,Shree Mahalakshmi's House of Wax,Museum,3.0,- Ratnagiri Museum
2,Jaigad Light House,Tourist attraction,4.3,- Ratnagiri Tourist attraction
3,Shree Ganpatipule Mandir,Temple,4.7,"Temple, believed to be hundreds of years old, ..."
4,Magic Garden,Park,4.1,- Ratnagiri Park

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=200,stop_words='english')

In [30]:
vector = cv.fit_transform(new['tags']).toarray()

In [31]:
vector.shape

(417, 200)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity = cosine_similarity(vector)

In [34]:
similarity

array([[1.        , 0.70710678, 0.19245009, ..., 0.        , 0.        ,
        0.        ],
       [0.70710678, 1.        , 0.40824829, ..., 0.        , 0.        ,
        0.        ],
       [0.19245009, 0.40824829, 1.        , ..., 0.40824829, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.40824829, ..., 1.        , 0.14433757,
        0.13363062],
       [0.        , 0.        , 0.        , ..., 0.14433757, 1.        ,
        0.46291005],
       [0.        , 0.        , 0.        , ..., 0.13363062, 0.46291005,
        1.        ]])

In [35]:
tourist1[tourist1['Place_Name'] == 'Prachin Konkan'].index[0]

0

In [36]:
def recommend(place):
    city = []
    index = new[new['Place_Category'] == place].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(tourist1.iloc[i[0]].Place_Name)
        city.append(tourist1.iloc[i[0]].Place_City)
    
    return city

In [45]:
recommend('Beach')

Ganpatipule Beach
Bhandarpule Beach
Advika Beach
Guhagar beach.
Mirya beach

[['Ratnagiri'], ['Ratnagiri'], ['Ratnagiri'], ['Ratnagiri'], ['Ratnagiri']]

In [38]:
# import pickle
# pickle.dump(new,open('new.pkl','wb'))
# pickle.dump(similarity,open('similarity.pkl','wb'))
# pickle.dump(tourist1,open('tourist1.pkl','wb'))